### ISSUE TITLE
BEAR.Sundayのbootstrap/api.phpからputメソッドを発行したときにパラメータが渡ってこない

### ISSUE THREAD

**Issue by ritalin** [bearsunday/BEAR.AuraRouterModule#3]
現行、CliRouterによるputメソッドの処理は、CliRouterで標準入力にクエリパラメータを渡し、
HttpMethodParamsで拾うという形になっていると思います。

標準入力を介した受け渡しをするために、setインジェクションでCliRouterが保持する標準入力プロパティ(= stdIn)の値を差し替えていますが、AuraRouterProviderではHttpMethodParamsを直接インスタンス化しているために、HttpMethodParamsの標準入力プロパティ(= stdIn)には注入されないため、パラメータの受け渡しに不整合が起きていることが原因のように思えます。

AuraRouterProviderにおいて、HttpMethodParamsInterfaceを注入するよう変更することで問題を解決できることは確認しました。

**Comment by ritalin** [comment]
カスタムのCliModuleを利用している際に遭遇しましたが、HttpMethodParamsの直接のインスタンス化に起因しているため、組み込みのCliRouterでも同様に発現するとは思います（未確認ですが）

**Comment by koriym** [comment]
報告ありがとうございます。

検証可能なコードと、できればその問題を修正するコードも一緒にPRしてもらっていいでしょうか？
レビューします！（一旦このissueは閉じます）

**Comment by koriym** [comment]
今日リリースした`BEAR.Sunday 1.0.1`で修正されているかもしれません。
